#!/usr/bin/env bash
# ============================================================
#  cka-helm-practice · demo/record-demo.sh
#
#  Records a scripted terminal walkthrough of the exam suite and
#  turns it into a GIF and an animated SVG for the README and for
#  LinkedIn.
#
#  Run it on the machine that has the cluster (Killercoda, kind,
#  minikube). It types the commands for you at a readable pace,
#  so the recording is reproducible instead of depending on how
#  fast you type.
#
#    ./demo/record-demo.sh                 # exam 1, cast + gif + svg
#    EXAM=3 ./demo/record-demo.sh          # record exam 3 instead
#    ./demo/record-demo.sh --cast-only     # just the .cast, convert later
#    ./demo/record-demo.sh --render-only   # convert an existing .cast
#
#  Requirements
#    asciinema   the recorder            https://asciinema.org
#    agg         cast -> GIF             cargo install --git https://github.com/asciinema/agg
#    svg-term    cast -> SVG (optional)  npm i -g svg-term-cli
#
#  --cast-only needs only asciinema, and .cast files can be
#  converted anywhere, so recording on the cluster host and
#  rendering on your laptop is the usual split.
# ============================================================
set -uo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
OUT="$HERE/out"
EXAM="${EXAM:-1}"
NAME="${NAME:-cka-helm-practice-exam${EXAM}}"
CAST="$OUT/${NAME}.cast"

# Typing speed and pauses. Slower is more readable; these are tuned so a
# ~45s recording stays legible when GitHub scales it down.
TYPE_DELAY="${TYPE_DELAY:-0.035}"   # seconds per character
PAUSE_SHORT="${PAUSE_SHORT:-0.8}"   # after a command finishes
PAUSE_LONG="${PAUSE_LONG:-2.2}"     # after something worth reading

# Terminal geometry. 100x30 is a good compromise: wide enough for helm
# output, small enough that the text stays sharp in a README.
COLS="${COLS:-100}"
ROWS="${ROWS:-30}"

G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; BO=$'\e[1m'; D=$'\e[2m'; N=$'\e[0m'
ok(){   printf "  ${G}✔${N} %s\n" "$*"; }
warn(){ printf "  ${Y}!${N} %s\n" "$*"; }
die(){  printf "  ${R}✘${N} %s\n" "$*"; exit 1; }

MODE="all"
case "${1:-}" in
  --cast-only)   MODE="cast" ;;
  --render-only) MODE="render" ;;
  ""|--all)      MODE="all" ;;
  -h|--help)     sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  *)             die "unknown option: $1  (try --help)" ;;
esac

mkdir -p "$OUT"

# ── the script the recording plays out ──────────────────────
# One command per line. Lines starting with # are shown as comments
# (typed out, but not executed), which is how the narration works.
# Lines starting with @ are pauses in seconds.
demo_script(){
  case "$EXAM" in
    3)
      cat <<'SCRIPT'
# 13 Helm tasks for the CKA, graded against a real cluster.
@1
exam3
@3
# Task 2 is the one everybody gets wrong.
q3 2
@3
# --skip-crds looks right. It does nothing to this chart.
helm template argocd argo/argo-cd --version 7.9.1 -n argocd --skip-crds | grep -c 'kind: CustomResourceDefinition'
@2
# The CRDs are in templates/, not crds/. So it needs the chart's own value.
helm template argocd argo/argo-cd --version 7.9.1 -n argocd --set crds.install=false > ~/answers3/q2.yaml
grep -c 'kind: CustomResourceDefinition' ~/answers3/q2.yaml
@2
# The grader reads the file and the cluster, not my answer.
grade3 2
@3
# Stuck? Every task has a walkthrough that explains the trap.
explain3 2
@6
grade3
@4
SCRIPT
      ;;
    2)
      cat <<'SCRIPT'
# Exam 2: repos, values precedence, --atomic, subcharts, broken charts.
@1
exam2
@3
q2 4
@3
# Two values files. The last -f wins, key by key.
cat ~/exam2/base.yaml ~/exam2/override.yaml
@2
helm install shop-app extrarepo/web-stack --version 1.0.0 -n shop --create-namespace -f ~/exam2/base.yaml -f ~/exam2/override.yaml
@2
helm get values shop-app -n shop
@2
grade2 4
@3
grade2
@4
SCRIPT
      ;;
    *)
      cat <<'SCRIPT'
# 13 Helm tasks for the CKA. You solve them on a real cluster.
@1
exam
@3
q 2
@3
# The grader checks the cluster, so let me look at it first.
kubectl get pods -n apps
@2
helm history legacy -n apps
@3
# Revision 3 is the broken upgrade. Roll back to the last good one.
helm rollback legacy 2 -n apps
@1
helm history legacy -n apps
@3
# Note the rollback APPENDED revision 4. It did not erase revision 3.
grade 2
@3
# No guessing: it inspects release status, revisions and stored values.
grade
@4
SCRIPT
      ;;
  esac
}

# ── the inner script that actually runs inside asciinema ────
# Written to a file because asciinema -c takes a single command.
build_player(){
  cat > "$OUT/.player.sh" <<PLAYER
#!/usr/bin/env bash
# Generated by record-demo.sh — replays the demo script with simulated typing.
set -uo pipefail
export PS1=''
# The exam scripts colour their output only when stdout is a tty AND TERM is
# usable. Inside asciinema stdout is a pty, so all that is missing is TERM.
export TERM="\${TERM:-xterm-256color}"
TYPE_DELAY=$TYPE_DELAY
PAUSE_SHORT=$PAUSE_SHORT
PAUSE_LONG=$PAUSE_LONG
PROMPT='\$ '

# Load the exam commands, so the recording shows 'exam3' rather than paths.
source "$ROOT/activate.sh" 2>/dev/null || true

type_out(){ # print a string one character at a time
  local s="\$1" i
  for (( i=0; i<\${#s}; i++ )); do
    printf '%s' "\${s:\$i:1}"
    sleep "\$TYPE_DELAY"
  done
}

run_line(){
  local line="\$1"
  case "\$line" in
    '')  return ;;
    @*)  sleep "\${line#@}"; return ;;
    '#'*)
      # Narration: type it as a shell comment, then just newline.
      printf '\e[1;36m%s\e[0m' "\$PROMPT"
      printf '\e[2m'; type_out "\$line"; printf '\e[0m\n'
      sleep "\$PAUSE_SHORT"
      return ;;
  esac
  printf '\e[1;36m%s\e[0m' "\$PROMPT"
  type_out "\$line"
  printf '\n'
  sleep 0.35
  eval "\$line" 2>&1 || true
  sleep "\$PAUSE_SHORT"
}

while IFS= read -r l; do run_line "\$l"; done < "$OUT/.script.txt"

printf '\e[1;36m%s\e[0m' "\$PROMPT"
sleep "\$PAUSE_LONG"
PLAYER
  chmod +x "$OUT/.player.sh"
}

# ── record ──────────────────────────────────────────────────
if [ "$MODE" != "render" ]; then
  command -v asciinema >/dev/null \
    || die "asciinema not found.  pip install asciinema   (or: brew install asciinema)"
  command -v kubectl >/dev/null && kubectl get nodes >/dev/null 2>&1 \
    || warn "no reachable cluster — the recording will show failures"

  demo_script > "$OUT/.script.txt"
  build_player

  rm -f "$CAST"
  printf "\n%s  Recording exam %s%s  %s(%sx%s, ~40s — do not touch the keyboard)%s\n\n" \
    "$BO" "$EXAM" "$N" "$D" "$COLS" "$ROWS" "$N"

  # --cols/--rows pin the geometry so the output does not depend on the
  # window this happens to run in. -q keeps asciinema's own banner out
  # of the recording.
  asciinema rec "$CAST" \
    --cols "$COLS" --rows "$ROWS" \
    --idle-time-limit 2 \
    --overwrite -q \
    -c "bash --noprofile --norc $OUT/.player.sh" \
    || die "recording failed"

  rm -f "$OUT/.player.sh" "$OUT/.script.txt"
  ok "cast written to $CAST"
fi

[ -f "$CAST" ] || die "no cast at $CAST — record one first (drop --render-only)"

if [ "$MODE" = "cast" ]; then
  printf "\n  Convert it later with:\n\n"
  printf "    agg --font-size 16 --theme asciinema %s %s/%s.gif\n\n" "$CAST" "$OUT" "$NAME"
  exit 0
fi

# ── render ──────────────────────────────────────────────────
if command -v agg >/dev/null; then
  # --font-size 16 keeps the GIF readable at README width; the default 14
  # goes fuzzy once GitHub scales it. --speed 1 keeps real timing.
  agg --font-size 16 --theme asciinema --speed 1 \
      "$CAST" "$OUT/${NAME}.gif" >/dev/null 2>&1 \
    && ok "GIF  $OUT/${NAME}.gif  ($(du -h "$OUT/${NAME}.gif" | cut -f1))" \
    || warn "agg failed"
else
  warn "agg not found — no GIF.  cargo install --git https://github.com/asciinema/agg"
fi

if command -v svg-term >/dev/null; then
  # An animated SVG is a fraction of the GIF's size and stays crisp on
  # retina screens. GitHub renders it in a README; LinkedIn does not.
  svg-term --in "$CAST" --out "$OUT/${NAME}.svg" \
           --window --width "$COLS" --height "$ROWS" >/dev/null 2>&1 \
    && ok "SVG  $OUT/${NAME}.svg  ($(du -h "$OUT/${NAME}.svg" | cut -f1))" \
    || warn "svg-term failed"
else
  warn "svg-term not found — no SVG.  npm i -g svg-term-cli"
fi

echo
printf "%s  Next%s\n\n" "$BO" "$N"
printf "    README    ![demo](demo/out/%s.gif)\n" "$NAME"
printf "    LinkedIn  upload the .gif directly — under 8 MB and it animates.\n"
printf "              If it is bigger, re-run with COLS=90 ROWS=26 or trim the script.\n\n"
printf "    %sGIF size is driven by the number of distinct frames, so longer%s\n" "$D" "$N"
printf "    %spauses are cheap and fast scrolling is expensive.%s\n\n" "$D" "$N"
